In [1]:
from bs4 import BeautifulSoup
from requests import get

In [2]:
url = 'https://www.truecar.com/used-cars-for-sale/listings/ford/mustang/location-wichita-ks/?engine[]=8%20Cylinder&engine[]=6%20Cylinder&searchRadius=5000&transmission[]=Manual'
r = get(url)
soup = BeautifulSoup(r.text, 'html.parser')


print(soup)

In [3]:
posts = soup.find_all('a', {'class': 'linkable order-2 vehicle-card-overlay'})
print(len(posts))

33


In [4]:
temp = soup.find_all('a', {'class':'page-link'})[9]['aria-label'].split(" ")[1]


In [5]:
import pandas as pd
data = {
    'Mustang':pd.DataFrame(),
    '350z': pd.DataFrame(),
    'WRX': pd.DataFrame(),
    'Miata': pd.DataFrame()
}

In [6]:
truecar = pd.read_excel(r'C:\Users\asix.NIAR\Desktop\Homework\DataScience\FinalProject\DS-Final-Project\CarData.xlsx', sheet_name=None)
ebay = pd.read_excel(r'C:\Users\asix.NIAR\Desktop\Homework\DataScience\FinalProject\DS-Final-Project\CarData_ebay.xlsx', sheet_name=None)
craigslist = pd.read_excel(r'C:\Users\asix.NIAR\Desktop\Homework\DataScience\FinalProject\DS-Final-Project\CarData_craigslist.xlsx', sheet_name=None)

for i in truecar.keys():
    truecar[i] = truecar[i].rename(columns={'Price:': 'Price', 'price': 'Price', 'odometer': 'Mileage'})
    truecar[i] = truecar[i][truecar[i]['Engine'].notna()]
    data[i] = data[i].append(truecar[i])
for i in ebay.keys():
    ebay[i] = ebay[i].rename(columns={'Price:': 'Price', 'price': 'Price', 'odometer': 'Mileage'})
    ebay[i] = ebay[i][ebay[i]['Engine'].notna()]
    data[i] = data[i].append(ebay[i])
for i in craigslist.keys():
    craigslist[i] = craigslist[i].rename(columns={'Price:': 'Price', 'price': 'Price', 'odometer': 'Mileage'})
    craigslist[i] = craigslist[i][craigslist[i]['Engine'].notna()]
    data[i] = data[i].append(craigslist[i])

KeyboardInterrupt: 

In [ ]:
temp = data.copy()
temp['Mustang'].columns

In [ ]:
temp['Mustang'][['Price', 'Engine', 'Mileage']]

In [ ]:
# writer = pd.ExcelWriter('AllData.xlsx', mode="w")
# for i in temp.keys():
#     temp[i] = temp[i][['Price', 'Engine', 'Mileage']]
#     test = temp[i]['Engine']
#     for j, k in enumerate(test):
#         if "6" in k:
#             temp[i]['Engine'].iloc[j] = "V6"
#         elif "8" in k:
#             temp[i]['Engine'].iloc[j] = "V8"
#         # elif "4" in k:
#         #     temp[i]['Engine'].iloc[j] = "I4"
        
#     temp[i]['Engine'] = test
#     temp[i].to_excel(writer, i)
# writer.save()



In [ ]:
del temp

In [93]:
import numpy as np
import pandas as pd

data = pd.read_excel('AllData.xlsx', sheet_name='Mustang')
test = data[['Engine', 'Mileage']].to_numpy()

In [94]:
theta = np.array([0, 0, 0])
ones = np.array([[1], [1]])
for i in range(2, len(test)):
    ones = np.concatenate([ones, [np.array([1])]])
test = np.concatenate([ones, test], axis=1)

In [254]:
theta = np.array([[0],[0],[0]]).astype('double').transpose()[0]
print(theta)

[0. 0. 0.]


In [103]:
y = data['Price'].to_numpy()
X = test.transpose()
print(X)

[[     1      1      1 ...      1      1      1]
 [     6      6      6 ...      8      8      8]
 [154079  60912 222873 ...  52405  52405  52405]]


In [146]:
# print(np.matmul(theta, X)-y)
X = X.astype('double')
print(np.sum(np.matmul(theta.transpose(), X)-y))
t1 = theta[0] -.01/616. * np.sum(np.matmul(theta, X)-y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [170]:
test = np.matmul(theta.transpose(), X)-y
print(test.shape, X[1].shape)

t2 = theta[1] - .01/616 * np.sum(np.matmul(test, X[1,:].transpose()))
t3 = theta[2] - .01/616 * np.sum(np.dot(test, X[2,:].transpose()))

(616,) (616,)


temp = ((X[1]-avg)/max)
print(temp)

In [172]:
for i in range(1500):
    test = np.matmul(theta.transpose(), X)-y
    t1 = theta[0] -.01/616. * np.sum(test)
    t2 = theta[1] - .01/616 * np.sum(np.dot(test, X[1, :].transpose()))
    t3 = theta[2] - .01/616 * np.sum(np.dot(test, X[2, :].transpose()))
    theta[0] = t1
    theta[1] = t2
    theta[2] = t3

<ipython-input-172-6017062a92f3>:5: RuntimeWarning: overflow encountered in matmul
  t3 = theta[2] - .01/616 * np.sum(np.matmul(test, X[2, :].transpose()))
<ipython-input-172-6017062a92f3>:2: RuntimeWarning: invalid value encountered in matmul
  test = np.matmul(theta.transpose(), X)-y


In [262]:
# test =np.matmul(theta, X) - 
temp_x = X[0:2]

In [265]:
test =np.matmul(theta, temp_x) - y
cost = 1/(2*len(y)) * np.sum(np.square(test))
t1 = theta[0] + .0003/616 * np.sum(test)
t2 = theta[1] + .0003/616 * np.sum(np.dot(test, X[1,:].transpose()))
# t3 = theta[2] + .0003/616 * np.sum(np.dot(test, X[2,:].transpose()))
print(cost)
theta[0] = t1
theta[1] = t2
# theta[2] = t3
print(theta)

370346209.06123406
[ -19.01664292 -132.09119154]


In [261]:
theta = np.array([[0],[0]]).astype('double').transpose()[0]
# t2 = theta[1:] - .0001/616 * np.sum(np.matmul(test, X[1:].transpose()))

In [248]:
print(theta)

[0. 0. 0.]


In [216]:
test = np.matmul(theta.transpose(), x) - y
cost = 1/(2*len(y)) * np.sum(np.square(test))
t1 = theta[0]

-8943.0

In [247]:
print(np.dot(test, X[1:].transpose()))
print(np.matmul(test, X[1:].transpose()))

[-8.91899056e+07 -7.28120291e+11]
[-8.91899056e+07 -7.28120291e+11]


In [230]:
del test